import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Bot, CheckCircle2, ChevronRight, Settings2, Sparkles } from "lucide-react";
import { useLocation } from "wouter";

export default function AIWorkspace() {
 const [, setLocation] = useLocation();
 const settings = trpc.ai.settings.useQuery();
 const ideas = trpc.ideas.list.useQuery({ limit: 8, offset: 0 });
 return <DashboardLayout><div className="mx-auto max-w-[1200px] space-y-6">
 <section className="relative overflow-hidden rounded-[2rem] via-slate-950 p-7 text-foreground sm:p-10"><div className="absolute -right-16 -top-16 h-64 w-64 rounded-full bg-card " /><div className="relative max-w-3xl"><Badge className="border-0 bg-card text-primary"><Bot className="mr-2 h-3.5 w-3.5" />OpenRouter AI workspace</Badge><h1 className="mt-5 text-3xl font-semibold tracking-tight sm:text-5xl">Use your model as a product strategy partner.</h1><p className="mt-4 text-base leading-8 text-muted-foreground">The AI layer is intentionally contextual: every response can see one idea, its three competitor records, monetization thesis, and implementation constraints.</p><div className="mt-7 flex flex-wrap gap-3"><Button onClick={() => setLocation("/settings")} className="bg-card text-foreground hover:bg-card"><Settings2 className="mr-2 h-4 w-4" />{settings.data?.configured ? "Change model" : "Configure model"}</Button><Button onClick={() => setLocation("/ideas")} variant="outline" className="border-border bg-transparent text-foreground hover:bg-card">Choose an idea <ArrowRight className="ml-2 h-4 w-4" /></Button></div></div></section>
 <div className="grid gap-4 md:grid-cols-3"><Card className="border-0 shadow-sm ring-1 ring-border/60"><CardContent className="p-5"><CheckCircle2 className="h-5 w-5 text-primary" /><p className="mt-4 text-sm font-semibold">Contextual prompts</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Ask about one product instead of losing signal in a generic chat.</p></CardContent></Card><Card className="border-0 shadow-sm ring-1 ring-border/60"><CardContent className="p-5"><Sparkles className="h-5 w-5 text-primary" /><p className="mt-4 text-sm font-semibold">Decision-ready output</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Generate validation plans, pricing tests, differentiation, and risk maps.</p></CardContent></Card><Card className="border-0 shadow-sm ring-1 ring-border/60"><CardContent className="p-5"><Bot className="h-5 w-5 text-primary" /><p className="mt-4 text-sm font-semibold">Your choice of model</p><p className="mt-1 text-sm leading-6 text-muted-foreground">OpenRouter model discovery keeps the provider layer flexible.</p></CardContent></Card></div>
 <Card className="border-0 shadow-sm ring-1 ring-border/60"><CardHeader className="flex flex-row items-end justify-between"><div><CardTitle>Pick an idea to analyze</CardTitle><p className="mt-1 text-sm text-muted-foreground">Open any detail page to start analysis or chat.</p></div><Badge variant={settings.data?.configured ? "default" : "outline"}>{settings.data?.configured ? "Model connected" : "Setup required"}</Badge></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-2">{ideas.data?.map(idea => <button key={idea.id} onClick={() => setLocation(`/ideas/${idea.id}`)} className="flex items-center justify-between rounded-2xl bg-muted/50 p-4 text-left transition hover:bg-muted"><div className="min-w-0"><div className="flex items-center gap-2"><Badge variant="secondary" className="text-[10px]">{idea.category}</Badge><span className="truncate text-xs text-muted-foreground">{idea.monetizationModel}</span></div><p className="mt-2 truncate text-sm font-semibold">{idea.title}</p></div><ChevronRight className="h-4 w-4 shrink-0 text-muted-foreground" /></button>)}</div></CardContent></Card>
 </div></DashboardLayout>;
}
