import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, ArrowRight, Bot, CheckCircle2, CircleDollarSign, Compass, Download, GitCompareArrows, Loader2, MessageSquare, ShieldAlert, Target, Users } from "lucide-react";
import { useMemo, useState } from "react";
import { Streamdown } from "streamdown";
import { useLocation, useRoute } from "wouter";

function levelStyle(level: string) { return level === "Low" ? "bg-emerald-50 text-emerald-700" : level === "Medium" ? "bg-amber-50 text-amber-700" : "bg-rose-50 text-rose-700"; }
function Section({ icon: Icon, title, children }: { icon: typeof Target; title: string; children: React.ReactNode }) { return <Card className="border-0 shadow-sm ring-1 ring-border/60"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Icon className="h-4 w-4 text-violet-600" />{title}</CardTitle></CardHeader><CardContent className="text-sm leading-7 text-muted-foreground">{children}</CardContent></Card>; }

export default function IdeaDetail() {
  const [, params] = useRoute("/ideas/:id");
  const [, setLocation] = useLocation();
  const id = useMemo(() => Number(params?.id), [params?.id]);
  const idea = trpc.ideas.get.useQuery({ id }, { enabled: Number.isFinite(id) });
  const aiSettings = trpc.ai.settings.useQuery();
  const analysis = trpc.ai.analyzeIdea.useMutation();
  const chat = trpc.ai.chat.useMutation();
  const [focus, setFocus] = useState("");
  const [prompt, setPrompt] = useState("");
  const [assistantOutput, setAssistantOutput] = useState("");
  const [threadId, setThreadId] = useState<number>();
  const historyInput = useMemo(() => threadId ? { threadId } : undefined, [threadId]);
  const history = trpc.ai.history.useQuery(historyInput ?? { threadId: 0 }, { enabled: !!threadId });
  if (idea.isLoading) return <DashboardLayout><div className="mx-auto max-w-6xl space-y-4"><div className="h-10 w-2/3 animate-pulse rounded bg-muted" /><div className="h-72 animate-pulse rounded-2xl bg-muted" /></div></DashboardLayout>;
  if (!idea.data) return <DashboardLayout><div className="mx-auto max-w-6xl py-20 text-center"><p className="text-lg font-semibold">Idea not found</p><Button className="mt-4" onClick={() => setLocation("/ideas")}>Back to library</Button></div></DashboardLayout>;
  const item = idea.data;
  const runAnalysis = () => analysis.mutate({ ideaId: item.id, focus: focus || undefined }, { onSuccess: result => { setAssistantOutput(result.content); setThreadId(result.threadId); } });
  const sendPrompt = () => { if (!prompt.trim()) return; chat.mutate({ ideaId: item.id, prompt: prompt.trim(), threadId }, { onSuccess: result => { setAssistantOutput(result.content); setThreadId(result.threadId); setPrompt(""); } }); };
  const downloadReport = (format: "markdown" | "pdf") => window.open(`/api/reports/idea/${item.id}/${format}`, "_blank", "noopener,noreferrer");
  return <DashboardLayout><div className="mx-auto max-w-[1400px] space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><button onClick={() => setLocation("/ideas")} className="flex items-center gap-2 text-sm text-muted-foreground transition hover:text-foreground"><ArrowLeft className="h-4 w-4" />Back to idea library</button><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => setLocation(`/compare?ids=${item.id},${Math.max(1, item.id === 1 ? 2 : 1)}`)}><GitCompareArrows className="mr-2 h-4 w-4" />Compare</Button><Button size="sm" variant="outline" onClick={() => downloadReport("markdown")}><Download className="mr-2 h-4 w-4" />Markdown</Button><Button size="sm" onClick={() => downloadReport("pdf")}><Download className="mr-2 h-4 w-4" />PDF</Button></div></div>
    <section className="rounded-[2rem] bg-slate-950 p-6 text-white shadow-xl sm:p-10"><div className="flex flex-col justify-between gap-8 lg:flex-row"><div className="max-w-3xl"><div className="flex flex-wrap items-center gap-2"><Badge className="border-0 bg-violet-500 text-white">{item.category}</Badge><Badge className="border-0 bg-white/10 text-slate-200">{item.subcategory}</Badge><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${item.competitionLevel === "Low" ? "bg-emerald-400/15 text-emerald-300" : "bg-amber-400/15 text-amber-300"}`}>{item.competitionLevel} competition</span></div><h1 className="mt-5 text-3xl font-semibold tracking-tight sm:text-5xl">{item.title}</h1><p className="mt-4 text-base leading-8 text-slate-300">{item.summary}</p></div><div className="grid min-w-[260px] grid-cols-2 gap-3 self-start"><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-slate-400">Signal score</p><p className="mt-2 text-2xl font-semibold">{item.competitionScore}<span className="text-sm text-slate-400">/100</span></p></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-slate-400">Revenue</p><p className="mt-2 text-sm font-semibold">{item.revenuePotential}</p></div></div></div></section>
    <div className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]"><div className="space-y-6"><div className="grid gap-4 md:grid-cols-2"><Section icon={Target} title="Target audience"><p>{item.targetAudience}</p></Section><Section icon={CircleDollarSign} title="Monetization thesis"><p>{item.monetizationModel}. Build the free experience around the first useful outcome; charge when the user needs history, collaboration, exports, or recurring automation.</p></Section></div><Section icon={Compass} title="Problem and solution"><div className="grid gap-6 md:grid-cols-2"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.14em] text-foreground">Problem</p><p>{item.problem}</p></div><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.14em] text-foreground">Solution</p><p>{item.solution}</p></div></div></Section><Section icon={CheckCircle2} title="Why this wedge can win"><p>{item.uniqueValue}</p></Section><div className="grid gap-4 md:grid-cols-2"><Section icon={Compass} title="MVP scope"><p>{item.mvpScope}</p></Section><Section icon={ShieldAlert} title="Risks and validation"><p>{item.risks}</p><Separator className="my-4" /><p className="text-foreground">Validation: {item.validationPlan}</p></Section></div><Section icon={CheckCircle2} title="Implementation plan"><p>{item.implementationPlan}</p></Section><Section icon={Users} title="Competitor map"><div className="space-y-4">{item.competitors.map((competitor, index) => <div key={competitor.id} className="rounded-2xl bg-muted/50 p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><p className="font-semibold text-foreground">{index + 1}. {competitor.name}</p><p className="mt-1 text-xs text-muted-foreground">{competitor.platform} · {competitor.positioning}</p></div><Badge className={levelStyle(competitor.threatLevel)}>{competitor.threatLevel} threat</Badge></div><div className="mt-4 grid gap-4 md:grid-cols-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-foreground">Strengths</p><p className="mt-1 text-xs leading-6">{competitor.strengths}</p></div><div><p className="text-xs font-semibold uppercase tracking-wider text-foreground">Weaknesses</p><p className="mt-1 text-xs leading-6">{competitor.weaknesses}</p></div><div><p className="text-xs font-semibold uppercase tracking-wider text-foreground">Our edge</p><p className="mt-1 text-xs leading-6">{competitor.differentiation}</p></div></div></div>)}</div></Section></div>
      <aside className="space-y-6"><Card className="border-0 bg-gradient-to-br from-violet-50 to-cyan-50 shadow-sm ring-1 ring-violet-100"><CardHeader><CardTitle className="flex items-center gap-2"><Bot className="h-5 w-5 text-violet-600" />AI product strategist</CardTitle><p className="text-sm text-muted-foreground">{aiSettings.data?.configured ? `Using ${aiSettings.data.modelLabel || aiSettings.data.selectedModel}` : "Connect OpenRouter in Settings to activate analysis."}</p></CardHeader><CardContent><Textarea value={focus} onChange={event => setFocus(event.target.value)} placeholder="Optional focus: pricing, distribution, technical scope…" className="min-h-24 bg-white/80" /><Button onClick={runAnalysis} disabled={!aiSettings.data?.configured || analysis.isPending} className="mt-3 w-full">{analysis.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <SparklesIcon />}Run full analysis</Button>{!aiSettings.data?.configured && <Button variant="link" className="mt-2 w-full" onClick={() => setLocation("/settings")}>Open AI settings <ArrowRight className="ml-2 h-4 w-4" /></Button>}</CardContent></Card><Card className="border-0 shadow-sm ring-1 ring-border/60"><CardHeader><CardTitle className="flex items-center gap-2"><MessageSquare className="h-4 w-4 text-cyan-600" />Ask about this idea</CardTitle></CardHeader><CardContent><Textarea value={prompt} onChange={event => setPrompt(event.target.value)} placeholder="How can I validate demand in 14 days?" className="min-h-28" /><Button onClick={sendPrompt} disabled={!prompt.trim() || !aiSettings.data?.configured || chat.isPending} className="mt-3 w-full" variant="secondary">{chat.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <MessageSquare className="mr-2 h-4 w-4" />}Send to model</Button></CardContent></Card>{(history.data?.length || assistantOutput) ? <Card className="border-0 shadow-sm ring-1 ring-border/60"><CardHeader><CardTitle className="flex items-center gap-2 text-sm"><MessageSquare className="h-4 w-4 text-violet-600" />Conversation history</CardTitle></CardHeader><CardContent className="space-y-4">{history.data?.map(message => <div key={message.id} className={`rounded-2xl p-4 ${message.role === "user" ? "ml-5 bg-muted" : "mr-5 bg-violet-50"}`}><div className="mb-2 flex items-center justify-between text-[11px] font-semibold uppercase tracking-wider text-muted-foreground"><span>{message.role === "user" ? "You" : "AI strategist"}</span>{message.model && <span className="max-w-[180px] truncate normal-case tracking-normal">{message.model}</span>}</div>{message.role === "assistant" ? <div className="prose prose-sm max-w-none"><Streamdown>{message.content}</Streamdown></div> : <p className="whitespace-pre-wrap text-sm leading-6">{message.content}</p>}</div>)}{!history.data?.length && assistantOutput ? <div className="prose prose-sm max-w-none"><Streamdown>{assistantOutput}</Streamdown></div> : null}</CardContent></Card> : null}</aside>
    </div>
  </div></DashboardLayout>;
}
function SparklesIcon() { return <Bot className="mr-2 h-4 w-4" />; }
