import PDFDocument from "pdfkit";
import type { Response } from "express";

type CompetitorReport = {
  name: string; platform: string; url?: string | null; positioning: string;
  strengths: string; weaknesses: string; differentiation: string; monetization: string; threatLevel: string;
};

type IdeaReport = {
  id: number; title: string; category: string; subcategory: string; summary: string;
  targetAudience: string; problem: string; solution: string; uniqueValue: string;
  monetizationModel: string; competitionLevel: string; competitionScore: number;
  revenuePotential: string; mvpScope: string; implementationPlan: string;
  validationPlan: string; risks: string; competitors: CompetitorReport[];
};

const clean = (value: unknown) => String(value ?? "").replace(/\r/g, "").trim();
const mdList = (items: string[]) => items.map(item => `- ${clean(item)}`).join("\n");

export function ideaToMarkdown(idea: IdeaReport) {
  const competitors = idea.competitors.map((competitor, index) => `### ${index + 1}. ${competitor.name}\n\n| Field | Analysis |\n| --- | --- |\n| Platform | ${clean(competitor.platform)} |\n| Positioning | ${clean(competitor.positioning)} |\n| Strengths | ${clean(competitor.strengths)} |\n| Weaknesses | ${clean(competitor.weaknesses)} |\n| Differentiation opportunity | ${clean(competitor.differentiation)} |\n| Monetization | ${clean(competitor.monetization)} |\n| Threat | ${clean(competitor.threatLevel)} |`).join("\n\n");
  return `# ${clean(idea.title)}\n\n> App Idea Hub opportunity report\n\n## Snapshot\n\n| Field | Value |\n| --- | --- |\n| Category | ${clean(idea.category)} |\n| Subcategory | ${clean(idea.subcategory)} |\n| Target audience | ${clean(idea.targetAudience)} |\n| Monetization | ${clean(idea.monetizationModel)} |\n| Competition | ${clean(idea.competitionLevel)} (${idea.competitionScore}/100) |\n| Revenue potential | ${clean(idea.revenuePotential)} |\n\n## Thesis\n\n**Summary.** ${clean(idea.summary)}\n\n**Problem.** ${clean(idea.problem)}\n\n**Solution.** ${clean(idea.solution)}\n\n**Unique value.** ${clean(idea.uniqueValue)}\n\n## MVP scope\n\n${clean(idea.mvpScope)}\n\n## Implementation plan\n\n${clean(idea.implementationPlan)}\n\n## Validation plan\n\n${clean(idea.validationPlan)}\n\n## Risks\n\n${clean(idea.risks)}\n\n## Competitor map\n\n${competitors}\n\n---\n\nGenerated by App Idea Hub.`;
}

export function comparisonToMarkdown(ideas: IdeaReport[]) {
  const header = `# Idea comparison\n\n> App Idea Hub side-by-side decision brief\n\n| Dimension | ${ideas.map(idea => clean(idea.title)).join(" | ")} |\n| --- | ${ideas.map(() => "---").join(" | ")} |`;
  const rows = [
    ["Category", ...ideas.map(idea => idea.category)],
    ["Audience", ...ideas.map(idea => idea.targetAudience)],
    ["Revenue potential", ...ideas.map(idea => idea.revenuePotential)],
    ["Competition", ...ideas.map(idea => `${idea.competitionLevel} (${idea.competitionScore}/100)`)],
    ["Monetization", ...ideas.map(idea => idea.monetizationModel)],
    ["Unique value", ...ideas.map(idea => idea.uniqueValue)],
    ["MVP scope", ...ideas.map(idea => idea.mvpScope)],
  ].map(row => `| ${row.map(clean).join(" | ")} |`).join("\n");
  const competitorRows = ideas.flatMap(idea => idea.competitors.map(competitor => `| ${clean(idea.title)} | ${clean(competitor.name)} | ${clean(competitor.strengths)} | ${clean(competitor.weaknesses)} | ${clean(competitor.differentiation)} |`)).join("\n");
  return `${header}\n${rows}\n\n## Competitor strengths and weaknesses\n\n| Idea | Competitor | Strengths | Weaknesses | Differentiation angle |\n| --- | --- | --- | --- | --- |\n${competitorRows}\n\n---\n\nGenerated by App Idea Hub.`;
}

function writePdfText(doc: PDFKit.PDFDocument, title: string, markdown: string) {
  doc.fontSize(20).fillColor("#111827").text(title, { paragraphGap: 10 });
  doc.fontSize(10).fillColor("#374151");
  for (const rawLine of markdown.split("\n")) {
    const line = rawLine.trim();
    if (!line) { doc.moveDown(0.5); continue; }
    if (line.startsWith("# ")) doc.fontSize(18).fillColor("#111827").text(line.slice(2), { paragraphGap: 6 });
    else if (line.startsWith("## ")) doc.fontSize(14).fillColor("#4f46e5").text(line.slice(3), { paragraphGap: 5 });
    else if (line.startsWith("### ")) doc.fontSize(12).fillColor("#111827").text(line.slice(4), { paragraphGap: 4 });
    else if (line.startsWith("|")) doc.fontSize(8).fillColor("#374151").text(line.replace(/\|/g, "  •  "), { paragraphGap: 2 });
    else if (line.startsWith("- ")) doc.fontSize(9).text(`• ${line.slice(2)}`, { paragraphGap: 2 });
    else doc.fontSize(9).fillColor("#374151").text(line, { paragraphGap: 4 });
  }
}

export function streamReportPdf(res: Response, filename: string, title: string, markdown: string) {
  const doc = new PDFDocument({ margin: 48, size: "A4" });
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
  doc.pipe(res);
  writePdfText(doc, title, markdown);
  doc.end();
}


type MarketingDescriptionReport = {
  appName: string;
  audience: string;
  keyword: string;
  tone: string;
  language: string;
  description: string;
  model: string;
  createdAt: Date | string;
};

export function marketingDescriptionToMarkdown(archive: MarketingDescriptionReport) {
  return `# ${clean(archive.appName)}\n\n> App Idea Hub marketing copy archive\n\n| Field | Value |\n| --- | --- |\n| Audience | ${clean(archive.audience)} |\n| Primary keyword | ${clean(archive.keyword)} |\n| Tone | ${clean(archive.tone)} |\n| Language | ${clean(archive.language)} |\n| Model | ${clean(archive.model)} |\n| Generated | ${new Date(archive.createdAt).toLocaleString()} |\n\n## Description\n\n${clean(archive.description)}\n\n---\n\nGenerated by App Idea Hub.`;
}
