import type { CompetitionLevel, IdeaCategory, MonetizationModel } from "../drizzle/schema";
import { explicitCompetitors } from "./explicitCompetitors";

export type SeedCompetitor = {
  name: string; platform: string; url: string; positioning: string;
  strengths: string; weaknesses: string; differentiation: string;
  monetization: string; threatLevel: CompetitionLevel;
};
export type SeedIdea = {
  slug: string; title: string; category: IdeaCategory; subcategory: string;
  summary: string; targetAudience: string; problem: string; solution: string;
  uniqueValue: string; monetizationModel: MonetizationModel;
  competitionLevel: CompetitionLevel; competitionScore: number;
  revenuePotential: "Moderate" | "Strong" | "Very strong";
  mvpScope: string; implementationPlan: string; validationPlan: string;
  risks: string; tags: string[]; competitors: SeedCompetitor[];
};
type Blueprint = { title: string; subcategory: string; audience: string; angle: string; model: MonetizationModel; level: CompetitionLevel; revenue: SeedIdea["revenuePotential"]; tags: string[] };
const b = (title: string, subcategory: string, audience: string, angle: string, model: MonetizationModel, level: CompetitionLevel, revenue: Blueprint["revenue"], tags: string[]): Blueprint => ({ title, subcategory, audience, angle, model, level, revenue, tags });
function slugify(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); }
function makeIdea(category: IdeaCategory, blueprint: Blueprint, index: number): SeedIdea {
  const slug = slugify(blueprint.title) + "-" + (index + 1);
  const competitionScore = blueprint.level === "Low" ? 28 + (index % 16) : blueprint.level === "Medium" ? 48 + (index % 18) : 70 + (index % 18);
  return { slug, title: blueprint.title, category, subcategory: blueprint.subcategory,
    summary: blueprint.title + " is a focused mobile product for " + blueprint.audience + ". Its wedge is " + blueprint.angle + ".",
    targetAudience: blueprint.audience, problem: "Users in this segment rely on generic tools, manual notes, or fragmented advice. That creates friction around " + blueprint.angle + ".",
    solution: "Build a Flutter-first workflow that makes the core action possible in under two minutes, keeps essential data available offline, and produces a useful export or shareable result.",
    uniqueValue: "The advantage is a guided workflow for " + blueprint.audience + " with language, defaults, and metrics generic products do not prioritize.",
    monetizationModel: blueprint.model, competitionLevel: blueprint.level, competitionScore, revenuePotential: blueprint.revenue,
    mvpScope: "Onboarding, one primary workflow, local persistence, searchable history, reminders, export/share, and a simple paywall or ad-free upgrade.",
    implementationPlan: "Phase 1: Flutter shell with Riverpod and local persistence. Phase 2: core workflow, analytics, and accessibility. Phase 3: sync, paid tier, and store optimization after retention evidence.",
    validationPlan: "Interview 10 target users, publish a waitlist page, recruit 20 beta users from one niche community, and measure activation, weekly retention, and willingness to pay.",
    risks: "Distribution may be harder than development; generic scope, privacy expectations, and premature monetization are the main risks.", tags: [...blueprint.tags, category.toLowerCase()],
    competitors: explicitCompetitors[slug] || [],
  };
}
const groups: [IdeaCategory, Blueprint[]][] = [
  ["Tools", [
    b("Offline Invoice Builder For Home Services", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Expiry Ledger For Small Restaurants", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Shift Handoff Log For Clinics", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Rental Contract Calendar For Small Landlords", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Mobile Stocktake For Corner Stores", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Local Vendor Quote Comparator", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Private Receipt Vault", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Repair Shop Job Card", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Cleaning Team Route Board", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Freelancer Scope Guard", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Community Event Budget Book", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Micro Warehouse Bin Finder", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Pet Care Client Notebook", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Arabic First Meeting Action Log", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Construction Photo Diary", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Subscription Renewal Radar", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Offline Route Sales Tracker", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("School Bus Attendance Board", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Shared Household Inventory", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Warranty Claim Organizer", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Simple Clinic Queue Display", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Barbershop Chair Scheduler", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Tutor Lesson Ledger", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Volunteer Roster For Ngos", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Farm Input Cost Notebook", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Local Delivery Proof App", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Wedding Vendor Checklist", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Personal Document Expiry Wallet", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Small Gym Member Notes", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Print Shop Quote Calculator", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Neighborhood Issue Tracker", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Simple Export Packing List", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Music Practice Room Booker", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Craft Market Seller Ledger", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Caregiver Visit Log", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Home Maintenance Timeline", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Local Club Membership Card", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Personal Study File Organizer", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Restaurant Prep List Timer", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
    b("Mobile Audit Checklist Builder", "Micro-SaaS workflow", "operators and small teams", "a narrow offline-first workflow", "Subscription", "Low", "Strong", ["tools"]),
  ]],
  ["Health", [
    b("Arabic Diabetes Meal Ledger", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Desk Worker Posture Coach", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Medication Routine For Caregivers", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Food Allergy Scanner Journal", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Sleep Routine For New Parents", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Low Impact Strength For Seniors", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Period Privacy Journal", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Caffeine Cutoff Coach", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Breathing For Exam Stress", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Pet Weight Vaccine Log", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Home Physio Routine Builder", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Hydration For Outdoor Workers", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Migraine Trigger Diary", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Asthma Action Reminder", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Food Prep For Kidney Care", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Work Break Stretch Cards", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Postpartum Recovery Tracker", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Dental Routine For Children", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Hearing Aid Care Log", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Vision Break Timer For Students", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Food Diary For Ibs Patterns", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Sleep Shift Planner", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Recovery Log For Runners", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Chair Yoga For Limited Mobility", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Blood Pressure Habit Log", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Healthy Lunchbox Planner", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Sun Exposure Reminder", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Care Plan Binder", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Meditation For Commuters", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Healthy Habit Buddy For Couples", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Voice Medication Notes", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Walking Club Challenge", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Allergen Free Pantry List", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Neck Pain Micro Routine", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Sleep Story Maker For Parents", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Healthy Cooking Portion Cards", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Hospital Visit Question List", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Training Load For Amateur Teams", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Period Pain Self Care Planner", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
    b("Mindful Eating Prompt Cards", "Wellness routine", "people managing a specific routine", "privacy-first guided follow-through", "Freemium", "Medium", "Strong", ["health"]),
  ]],
  ["Education", [
    b("Local Driving Theory Simulator", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Arabic Sign Language Starter", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Medical Vocabulary Cards", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Quran Revision Planner", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Trade Math Coach", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Ielts Speaking Partner Cards", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Micro Lessons For Restaurant Staff", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Parent Voice Story Studio", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Spelling Repair For Arabic Learners", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Pocket Science Lab", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Teacher Worksheet Generator", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Local History Flashcards", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Interview Practice For Trades", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("One Concept Coding Puzzles", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Music Practice Accountability", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Nursing Handoff Vocabulary", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Kids Money Missions", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Spaced Review For Certification", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Visual Vocabulary For Migrants", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Study Group Agenda Maker", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Coding Interview Drill Timer", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Early Reading Sound Coach", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Exam Mistake Journal", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Workplace Email English", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Practical Excel Mission Cards", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Signboard Reading For Travelers", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Micro History Podcast Companion", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Parent Teacher Notes Translator", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Home Repair Skills Academy", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Local Food Safety Quiz", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Geography Memory Atlas", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Reading Aloud Recorder", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Debate Argument Builder", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Learning Plan For Returning Adults", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Vocabulary From Personal Photos", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Exam Countdown Study Coach", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Sign Language Story Practice", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Tiny Business Accounting Course", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Pronunciation For Customer Support", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
    b("Offline Classroom Polls", "Micro-learning", "learners preparing for one outcome", "short practice tied to a measurable result", "Subscription", "Medium", "Strong", ["education"]),
  ]],
  ["AI", [
    b("Ai Brief Writer For Local Contractors", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Resume Tailor For One Profession", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Product Copy For Niche Sellers", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Local Trip Planner", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Contract Plain Language Reader", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Short Video Storyboarder", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Voice Note To Action List", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Home Repair Triage", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Local Dialect Rewriter", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Child Story Co Author", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Meeting Decision Register", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Research Digest For One Industry", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Grant Application Coach", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Lesson Differentiator", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Customer Complaint Classifier", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Personal Sop Builder", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Invoice Line Item Explainer", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Job Interview Roleplay For Trades", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Recipe Remixer For Allergies", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Privacy Policy Summarizer", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Retail Shelf Auditor", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Caregiver Shift Handoff", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Arabic Study Explainer", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai App Store Listing Critic", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Feature Prioritizer For Indie Founders", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Sales Call Follow Up Writer", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Form To Spreadsheet Extractor", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Accessibility Copy Checker", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Local Event Promoter", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Personal Knowledge Librarian", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Fleet Incident Reporter", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Parent School Message Simplifier", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Microcopy For Mobile Onboarding", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Nonprofit Impact Story Builder", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Recipe Cost Calculator", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Mobile Bug Reproduction Assistant", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Voice To Form For Field Teams", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Competitor Review Theme Miner", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Grant Budget Narrator", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
    b("Ai Customer Faq Maintainer", "AI workflow", "professionals with repetitive knowledge work", "a structured AI output with human review", "Usage-based", "High", "Very strong", ["ai"]),
  ]],
  ["Games", [
    b("Local Dialect Crossword", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("One Tap Food Truck Rush", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Ar Tabletop Maze", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Zen Balcony Garden", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Heritage Runner", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Two Minute Detective", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Pocket Bazaar Manager", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Memory Match For Seniors", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Physics Line Rescue", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Night Shift Tower", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Cozy Train Route", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Sound Guess Nature", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Balance Ball Sensor Challenge", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Merge Farm Desert Edition", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Color By Pattern Mosque Art", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Courier Bike City", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Tiny Aquarium Keeper", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Escape Room The Archive", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Market Day Memory", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Mini Golf Blueprint", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Word Ladder In Arabic", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Street Food Match", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Cloud Painter", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Silent Signal", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Build A Boat Weekend", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Quiz Duel For Families", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Garden Pest Detective", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Rooftop Delivery Puzzle", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Pocket Orchestra", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Museum Night Hunt", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Pixel Repair Shop", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Island Weather Survival", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Letter Market", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Calm Traffic Controller", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Treasure Map Fold", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Farmers Market Tycoon Lite", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Robot Repair Relay", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Story Choices The Caravan", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Paper Plane Workshop", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
    b("Night Market Mahjong Mini", "Casual game", "players seeking short repeatable sessions", "a distinctive mechanic with local or niche identity", "Ads", "Medium", "Strong", ["games"]),
  ]],
];
export const seedIdeas: SeedIdea[] = groups.flatMap(([category, items]) => items.map((item, index) => makeIdea(category, item, index)));
if (seedIdeas.length !== 200) throw new Error("Expected 200 ideas, got " + seedIdeas.length);
if (seedIdeas.some(idea => idea.competitors.length !== 3)) throw new Error("Every seeded idea must have exactly three competitors");
export const seedSummary = { ideas: seedIdeas.length, competitors: seedIdeas.reduce((sum, idea) => sum + idea.competitors.length, 0), categories: { Tools: 40, Health: 40, Education: 40, AI: 40, Games: 40 } } as const;
export const seedDataVersion = "ideas-200-v2-explicit-competitors" as const;
export type SeedDataVersion = typeof seedDataVersion;
export default seedIdeas;

// These are opportunity hypotheses and public product-positioning notes, not user-generated testimonials.
